"""empty message

Revision ID: 07c44256b8d8
Revises: 18f1d056ac5e
Create Date: 2018-01-13 19:26:08.892437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07c44256b8d8'
down_revision = '18f1d056ac5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('songs_song_id_fkey', 'songs', type_='foreignkey')
    op.drop_constraint('songs_user_id_fkey', 'songs', type_='foreignkey')
    op.drop_column('songs', 'played_at')
    op.drop_column('songs', 'song_id')
    op.drop_column('songs', 'duration')
    op.drop_column('songs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('songs', sa.Column('played_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('songs_user_id_fkey', 'songs', 'users', ['user_id'], ['id'])
    op.create_foreign_key('songs_song_id_fkey', 'songs', 'songs', ['song_id'], ['id'])
    op.drop_table('streams')
    # ### end Alembic commands ###
