"""empty message

Revision ID: 228bba4edc6f
Revises: 92ddede47972
Create Date: 2018-01-13 19:04:28.911020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228bba4edc6f'
down_revision = '92ddede47972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('spotify_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'spotify_id')
    # ### end Alembic commands ###
