"""empty message

Revision ID: 866ced867e66
Revises: 
Create Date: 2017-12-29 19:53:17.006487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866ced867e66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('profile_image', sa.Text(), nullable=True),
    sa.Column('spotify_id', sa.Integer(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('wallet_address', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
