"""empty message

Revision ID: f226666b8429
Revises: 228bba4edc6f
Create Date: 2018-01-13 19:13:24.086418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f226666b8429'
down_revision = '228bba4edc6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'spotify_id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'spotify_id',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
